"""Version-pinned PUBLIC function privilege handling for migration 0004."""

from alembic import op

_SNAPSHOT_ROLE = "science_workbench_0004_public_execute_snapshot"


def harden_public_function_execute() -> None:
    """Preserve the 0003 PUBLIC surface, then remove it at revision 0004."""
    op.execute(
        "DO $$ DECLARE owner_oid oid; owner_name name; public_execute boolean; "
        "public_grantable boolean; schema_public_execute boolean; "
        "schema_public_grantable boolean; snapshot_count bigint; snapshot_hash "
        "text; marker text; BEGIN IF "
        f"to_regrole('{_SNAPSHOT_ROLE}') IS NOT NULL THEN RAISE EXCEPTION "
        "'reserved PUBLIC function privilege snapshot role already exists' USING "
        "ERRCODE = '42710'; END IF; SELECT oid, rolname INTO owner_oid, owner_name "
        "FROM pg_roles WHERE rolname = current_user; SELECT COALESCE(bool_or(entry."
        "privilege_type = 'EXECUTE'), false), COALESCE(bool_or(entry.is_grantable) "
        "FILTER (WHERE entry.privilege_type = 'EXECUTE'), false) INTO "
        "public_execute, public_grantable FROM LATERAL aclexplode(COALESCE((SELECT "
        "defaults.defaclacl FROM pg_default_acl defaults WHERE defaults.defaclrole "
        "= owner_oid AND defaults.defaclnamespace = 0 AND "
        "defaults.defaclobjtype = 'f'), acldefault('f', owner_oid))) entry WHERE "
        "entry.grantee = 0; SELECT COALESCE(bool_or(entry.privilege_type = "
        "'EXECUTE'), false), COALESCE(bool_or(entry.is_grantable) FILTER (WHERE "
        "entry.privilege_type = 'EXECUTE'), false) INTO schema_public_execute, "
        "schema_public_grantable FROM pg_default_acl defaults JOIN pg_namespace "
        "namespace ON namespace.oid = defaults.defaclnamespace, LATERAL "
        "aclexplode(defaults.defaclacl) entry WHERE defaults.defaclrole = owner_oid "
        "AND defaults.defaclobjtype = 'f' AND namespace.nspname = 'public' AND "
        "entry.grantee = 0; IF public_grantable OR schema_public_grantable OR EXISTS "
        "(SELECT 1 FROM pg_proc "
        "p JOIN pg_namespace n ON n.oid = p.pronamespace, LATERAL aclexplode("
        "COALESCE(p.proacl, acldefault('f', p.proowner))) entry WHERE n.nspname = "
        "'public' AND entry.grantee = 0 AND entry.privilege_type "
        "= 'EXECUTE' AND entry.is_grantable) THEN RAISE EXCEPTION 'PUBLIC function "
        "EXECUTE grant option is unsupported' USING ERRCODE = '55000'; END IF; "
        "IF EXISTS (SELECT 1 FROM pg_default_acl defaults LEFT JOIN pg_namespace "
        "namespace ON namespace.oid = defaults.defaclnamespace, LATERAL "
        "aclexplode(defaults.defaclacl) entry WHERE defaults.defaclobjtype = 'f' "
        "AND entry.grantee = 0 AND entry.privilege_type = 'EXECUTE' AND (defaults."
        "defaclrole <> owner_oid OR (defaults.defaclnamespace <> 0 AND namespace."
        "nspname <> 'public'))) THEN RAISE EXCEPTION 'PUBLIC routine default owned "
        "outside the migration boundary' USING ERRCODE = '55000'; END IF; "
        "SELECT count(*), md5(COALESCE(string_agg(p.oid::text || ':' || entry."
        "is_grantable::text, ',' ORDER BY p.oid), '')) INTO snapshot_count, "
        "snapshot_hash FROM pg_proc p JOIN pg_namespace n ON n.oid = p."
        "pronamespace, LATERAL aclexplode(COALESCE(p.proacl, acldefault('f', p."
        "proowner))) entry WHERE n.nspname = 'public' AND entry.grantee = 0 AND "
        "entry.privilege_type = 'EXECUTE'; "
        f"CREATE ROLE {_SNAPSHOT_ROLE} WITH NOLOGIN NOSUPERUSER NOCREATEDB "
        "NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS; marker := format("
        "'science-workbench-0004-public-function-default|%s|%s|%s|%s|%s|%s|%s', "
        "owner_oid, public_execute, public_grantable, schema_public_execute, "
        "schema_public_grantable, snapshot_count, snapshot_hash); EXECUTE "
        "format('COMMENT ON ROLE "
        f"{_SNAPSHOT_ROLE} IS %L', marker); EXECUTE format('ALTER DEFAULT "
        "PRIVILEGES FOR ROLE %I REVOKE EXECUTE ON FUNCTIONS FROM "
        "PUBLIC', owner_name); EXECUTE format('ALTER DEFAULT PRIVILEGES FOR ROLE "
        "%I IN SCHEMA public REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC', owner_name); "
        "END $$"
    )
    op.execute(
        "DO $$ DECLARE procedure_oid oid; BEGIN FOR procedure_oid IN SELECT p.oid "
        "FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace, LATERAL "
        "aclexplode(COALESCE(p.proacl, acldefault('f', p.proowner))) entry WHERE "
        "n.nspname = 'public' AND entry.grantee = 0 AND "
        "entry.privilege_type = 'EXECUTE' LOOP EXECUTE format('GRANT EXECUTE ON "
        f"ROUTINE %s TO {_SNAPSHOT_ROLE}', procedure_oid::regprocedure); END LOOP; "
        "END $$"
    )
    op.execute("REVOKE EXECUTE ON ALL ROUTINES IN SCHEMA public FROM PUBLIC")


def restore_public_function_execute() -> None:
    """Restore the captured 0003 PUBLIC function surface and discard the snapshot."""
    op.execute(
        "DO $$ DECLARE snapshot_oid oid; procedure_oid oid; owner_oid oid; "
        "owner_name name; marker text; public_execute boolean; public_grantable "
        "boolean; schema_public_execute boolean; schema_public_grantable boolean; "
        "snapshot_count bigint; snapshot_hash text; actual_count bigint; actual_hash "
        "text; BEGIN snapshot_oid := "
        f"to_regrole('{_SNAPSHOT_ROLE}'); IF snapshot_oid IS NULL THEN RETURN; END "
        "IF; IF EXISTS (SELECT 1 FROM pg_auth_members WHERE roleid = snapshot_oid "
        "OR member = snapshot_oid) THEN RAISE EXCEPTION 'PUBLIC function privilege "
        "snapshot role has unexpected memberships' USING ERRCODE = '55000'; END "
        "IF; SELECT rolcanlogin OR rolsuper OR rolcreatedb OR rolcreaterole OR "
        "rolinherit OR rolreplication OR rolbypassrls INTO public_grantable FROM "
        "pg_roles WHERE oid = snapshot_oid; IF public_grantable THEN RAISE "
        "EXCEPTION 'PUBLIC function privilege snapshot role is not confined' USING "
        "ERRCODE = '55000'; END IF; marker := shobj_description(snapshot_oid, "
        "'pg_authid'); IF marker !~ '^science-workbench-0004-public-function-"
        "default[|][0-9]+[|][tf][|][tf][|][tf][|][tf][|][0-9]+[|][0-9a-f]{32}$' "
        "THEN RAISE "
        "EXCEPTION 'PUBLIC function "
        "privilege snapshot marker is invalid' USING ERRCODE = '55000'; END IF; "
        "owner_oid := split_part(marker, '|', 2)::oid; public_execute := "
        "split_part(marker, '|', 3)::boolean; public_grantable := split_part(marker, "
        "'|', 4)::boolean; schema_public_execute := split_part(marker, '|', 5)::"
        "boolean; schema_public_grantable := split_part(marker, '|', 6)::boolean; "
        "snapshot_count := split_part(marker, '|', 7)::bigint; snapshot_hash := "
        "split_part(marker, '|', 8); SELECT rolname INTO owner_name "
        "FROM pg_roles WHERE oid = "
        "owner_oid; IF NOT FOUND THEN RAISE EXCEPTION 'PUBLIC function default "
        "privilege owner no longer exists' USING ERRCODE = '55000'; END IF; SELECT "
        "count(*), md5(COALESCE(string_agg(p.oid::text || ':' || entry."
        "is_grantable::text, ',' ORDER BY p.oid), '')) INTO actual_count, actual_hash "
        "FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace, LATERAL "
        "aclexplode(p.proacl) entry WHERE n.nspname = 'public' AND entry.grantee = "
        "snapshot_oid AND entry.privilege_type = 'EXECUTE'; IF actual_count <> "
        "snapshot_count OR actual_hash <> snapshot_hash THEN RAISE EXCEPTION "
        "'PUBLIC function privilege snapshot has changed' USING ERRCODE = '55000'; "
        "END IF; IF "
        "public_execute THEN EXECUTE format('ALTER DEFAULT PRIVILEGES FOR ROLE %I "
        "GRANT EXECUTE ON FUNCTIONS TO PUBLIC%s', owner_name, CASE "
        "WHEN public_grantable THEN ' WITH GRANT OPTION' ELSE '' END); END IF; IF "
        "schema_public_execute THEN EXECUTE format('ALTER DEFAULT PRIVILEGES FOR "
        "ROLE %I IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO PUBLIC%s', "
        "owner_name, CASE WHEN schema_public_grantable THEN ' WITH GRANT OPTION' "
        "ELSE '' END); END IF; FOR "
        "procedure_oid IN SELECT p.oid FROM pg_proc p JOIN pg_namespace n "
        "ON n.oid = p.pronamespace, LATERAL aclexplode(p.proacl) entry WHERE "
        "n.nspname = 'public' AND entry.grantee = snapshot_oid AND "
        "entry.privilege_type = 'EXECUTE' LOOP EXECUTE format('GRANT EXECUTE ON "
        "ROUTINE %s TO PUBLIC', procedure_oid::regprocedure); END LOOP; EXECUTE "
        f"'REVOKE ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA public FROM "
        f"{_SNAPSHOT_ROLE}'; EXECUTE 'DROP ROLE {_SNAPSHOT_ROLE}'; END $$"
    )
